"""empty message

Revision ID: 031b4726528f
Revises: 464e187b2d98
Create Date: 2022-01-03 10:49:21.968636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '031b4726528f'
down_revision = '464e187b2d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paste', sa.Column('date_created', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('paste', 'date_publish')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paste', sa.Column('date_publish', mysql.DATETIME(), nullable=True))
    op.drop_column('paste', 'date_created')
    # ### end Alembic commands ###
