"""empty message

Revision ID: 969672ce1d1a
Revises: 0d3ef5715453
Create Date: 2021-10-03 13:17:21.778436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '969672ce1d1a'
down_revision = '0d3ef5715453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=1000), nullable=False),
    sa.Column('code_title', sa.String(length=1000), nullable=False),
    sa.Column('code', sa.String(length=10000), nullable=False),
    sa.Column('languange', sa.String(length=1000), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_title', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('book_author', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('date_added', mysql.VARCHAR(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('codes')
    # ### end Alembic commands ###
